language: go
go:
  - 1.4.2
  - tip
sudo: required
before_install:
  - ./travis_install_capstone_stable.sh
  - ./genconst $HOME/src/capstone/bindings/python/capstone
  - ./genspec $HOME/src/capstone/tests
notifications:
  email:
    recipients:
      - travis@ben.iagu.net
